### ISSUE TITLE
NameError: name 'datetime' is not defined

### ISSUE THREAD

**Issue by victormbarriosb** [rushic24/tradingview-scraper#5]
`        for xi in x:
            xi= re.split('\[|:|,|\]', xi)
            print(xi)
            ind= int(xi[1])
            ts= datetime.fromtimestamp(float(xi[4])).strftime("%Y/%m/%d, %H:%M:%S")
            employee_writer.writerow([ind, ts, float(xi[5]), float(xi[6]), float(xi[7]), float(xi[8]), float(xi[9])])
            `

` ts= datetime.fromtimestamp(float(xi[4])).strftime("%Y/%m/%d, %H:%M:%S")`

I will try to solve it!

**Comment by rushic24** [comment]
are you sure you're using python3 ?
