### ISSUE TITLE
Hourly/daily

### ISSUE THREAD

**Issue by dmg809** [rushic24/tradingview-scraper#7]
What should I change in the code to get hourly/daily data?

**Comment by dmg809** [comment]
![image](https://user-images.githubusercontent.com/80600016/111079702-69b41780-84fb-11eb-80c0-ebbe08400de1.png)
1D

**Comment by euvgub** [comment]
'create_series', [cs, "s1", "s1", "symbol_1", time_frame, max_get_data]
'~m~74~m~{"m":"create_series","p":["cs_WkG6ZDRM8isa","s1","s1","symbol_1","60",300]}'
'~m~74~m~{"m":"create_series","p":["cs_WkG6ZDPM7isa","s1","s1","symbol_1","1D",300]}'

'~m~72~m~{"m":"modify_series","p":["cs_WkG6ZSPM9isa","s1","s1","symbol_1","1D"]}'
